# Generated by Django 6.0.2 on 2026-02-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='total_blocked_hours',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
