# Generated by Django 6.0.2 on 2026-03-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_deliverable_user_alter_plannedactivity_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverable',
            name='user',
        ),
        migrations.RemoveField(
            model_name='plannedactivity',
            name='user',
        ),
    ]
